### 基础课程信息获取测试
POST {{content_host}}/content/course/list?pageNo=2&pageSize=5
Content-Type: application/json

{
  "courseName": "测试"
}

### 树形目录查询
GET {{content_host}}/content/course-category/tree-nodes
Content-Type: application/json

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "",
  "st": "1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级",
  "tags": "",
  "grade": "204001",
  "description": "",
  "objectives": ""
}


### 根据id查找课程详细信息
GET {{content_host}}/content/course/40
Content-Type: application/json

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "companyName": null,
  "name": "SpringBoot核心",
  "users": "Springdddd",
  "tags": "Spring项目的快速构建",
  "mt": "1-3",
  "st": "1-3-1",
  "grade": "200003",
  "teachmode": "201001",
  "description": "课程系统性地深度探讨 Spring Boot",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOTInterview-questions.jpg",
  "charge": "201001",
  "price": 6,
  "qq": "123"
}


### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes
Content-Type: application/json

### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 [点击修改]"
}

### 修改课程计划,需要从数据库找到修改的课程计划id
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 22,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 179,
  "pname" : "第1节修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}


### 删除课程计划
DELETE {{content_host}}/content/teachplan/179

### 上移课程
POST {{content_host}}/content/teachplan/moveup/249

### 下移课程
POST {{content_host}}/content/teachplan/movedown/249

### 查询教师名单
GET  {{gateway_host}}/content/courseTeacher/list/75
# TODO：
### 添加教师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 75,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介"
}


### 修改课程教师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 75,
  "teacherName": "A老师",
  "position": "教师职位",
  "introduction": "教师简介",
  "photograph": null,
  "createDate": null
}

### 删除课程教师
DELETE  {{content_host}}/content/courseTeacher/75/22


### 删除课程
DELETE  {{content_host}}/content/course/87